---

- name: "Fetch telegraf installation package | Debian"
  action: get_url
          url={{telegraf_agent_base_download_uri}}{{ telegraf_agent_version }}-1_amd64.deb
          dest=/tmp/telegraf_{{ telegraf_agent_version }}-1_amd64.deb
          mode=0440

- name: "Install telegraf package | Debian"
  action: apt
          deb=/tmp/telegraf_{{ telegraf_agent_version }}-1_amd64.deb
          state=installed
  notify: "Restart Telegraf"
  sudo: yes
